import braintree

from flask import Flask, render_template, send_from_directory, request
app = Flask(__name__)

braintree.Configuration.configure(
    braintree.Environment.Sandbox,
    "23nd25g4kn7gnqbb",
    "8552x2ym5bvhsycp",
    "17f3279171d4fd90ee9cd5256be17abf"
)

@app.route("/")
def index():

    result = braintree.Customer.create({
      "first_name": 'Test',
      "last_name": 'User',
    })

    # store customer id generated by braintree
    custid = result.customer.id

    # Generate client token for the dropin ui
    client_token = braintree.ClientToken.generate({})

    return render_template('index.html', token=client_token, custid=custid)

@app.route("/step2", methods=['GET', 'POST'])
def step2():

    result = braintree.PaymentMethod.create({
      "customer_id": request.form["custid"],
      "payment_method_nonce": request.form["payment_method_nonce"],
    })

    return render_template('step2.html', result=result, custid=request.form["custid"])

@app.route("/step3", methods=['GET', 'POST'])
def step3():

    result = braintree.Transaction.sale({
        "amount": request.form["amount"],
        "customer_id": request.form["custid"],
        "payment_method_token": request.form["token"],
    })

    return render_template('step3.html', result=result, token=request.form["token"], custid=request.form["custid"])


@app.route('/public/<path:path>')
def send_public(path):
    return send_from_directory('public', path)

if __name__ == "__main__":
    app.run()
